server:
  port: 3001
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: location-service
  datasource:
    password: postgres
    url: jdbc:postgresql://covid-location-db:6002/
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none