server:
  port: 2001

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  application:
    name: vaccination-service
  datasource:
    password: postgres
    url: jdbc:postgresql://covid-vaccination-db:5433/
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none


eureka.instance.instance-id: ${spring.application.name}:${random.uuid}
